// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/auctions-service/protobuf/auctions_management_service.proto

package auctions_management_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartAuctionRequest struct {
	AuctionId            string   `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartAuctionRequest) Reset()         { *m = StartAuctionRequest{} }
func (m *StartAuctionRequest) String() string { return proto.CompactTextString(m) }
func (*StartAuctionRequest) ProtoMessage()    {}
func (*StartAuctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323b9ee31d05cb8c, []int{0}
}

func (m *StartAuctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartAuctionRequest.Unmarshal(m, b)
}
func (m *StartAuctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartAuctionRequest.Marshal(b, m, deterministic)
}
func (m *StartAuctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartAuctionRequest.Merge(m, src)
}
func (m *StartAuctionRequest) XXX_Size() int {
	return xxx_messageInfo_StartAuctionRequest.Size(m)
}
func (m *StartAuctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartAuctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartAuctionRequest proto.InternalMessageInfo

func (m *StartAuctionRequest) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

type StartAuctionResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartAuctionResponse) Reset()         { *m = StartAuctionResponse{} }
func (m *StartAuctionResponse) String() string { return proto.CompactTextString(m) }
func (*StartAuctionResponse) ProtoMessage()    {}
func (*StartAuctionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_323b9ee31d05cb8c, []int{1}
}

func (m *StartAuctionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartAuctionResponse.Unmarshal(m, b)
}
func (m *StartAuctionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartAuctionResponse.Marshal(b, m, deterministic)
}
func (m *StartAuctionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartAuctionResponse.Merge(m, src)
}
func (m *StartAuctionResponse) XXX_Size() int {
	return xxx_messageInfo_StartAuctionResponse.Size(m)
}
func (m *StartAuctionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartAuctionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartAuctionResponse proto.InternalMessageInfo

func (m *StartAuctionResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *StartAuctionResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SetStartTimeRequest struct {
	AuctionId            string   `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	StartTime            string   `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Timezone             string   `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStartTimeRequest) Reset()         { *m = SetStartTimeRequest{} }
func (m *SetStartTimeRequest) String() string { return proto.CompactTextString(m) }
func (*SetStartTimeRequest) ProtoMessage()    {}
func (*SetStartTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323b9ee31d05cb8c, []int{2}
}

func (m *SetStartTimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStartTimeRequest.Unmarshal(m, b)
}
func (m *SetStartTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStartTimeRequest.Marshal(b, m, deterministic)
}
func (m *SetStartTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStartTimeRequest.Merge(m, src)
}
func (m *SetStartTimeRequest) XXX_Size() int {
	return xxx_messageInfo_SetStartTimeRequest.Size(m)
}
func (m *SetStartTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStartTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetStartTimeRequest proto.InternalMessageInfo

func (m *SetStartTimeRequest) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

func (m *SetStartTimeRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *SetStartTimeRequest) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

type SetStartTimeResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStartTimeResponse) Reset()         { *m = SetStartTimeResponse{} }
func (m *SetStartTimeResponse) String() string { return proto.CompactTextString(m) }
func (*SetStartTimeResponse) ProtoMessage()    {}
func (*SetStartTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_323b9ee31d05cb8c, []int{3}
}

func (m *SetStartTimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStartTimeResponse.Unmarshal(m, b)
}
func (m *SetStartTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStartTimeResponse.Marshal(b, m, deterministic)
}
func (m *SetStartTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStartTimeResponse.Merge(m, src)
}
func (m *SetStartTimeResponse) XXX_Size() int {
	return xxx_messageInfo_SetStartTimeResponse.Size(m)
}
func (m *SetStartTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStartTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetStartTimeResponse proto.InternalMessageInfo

func (m *SetStartTimeResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SetStartTimeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CancelAuctionRequest struct {
	AuctionId            string   `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelAuctionRequest) Reset()         { *m = CancelAuctionRequest{} }
func (m *CancelAuctionRequest) String() string { return proto.CompactTextString(m) }
func (*CancelAuctionRequest) ProtoMessage()    {}
func (*CancelAuctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323b9ee31d05cb8c, []int{4}
}

func (m *CancelAuctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelAuctionRequest.Unmarshal(m, b)
}
func (m *CancelAuctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelAuctionRequest.Marshal(b, m, deterministic)
}
func (m *CancelAuctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelAuctionRequest.Merge(m, src)
}
func (m *CancelAuctionRequest) XXX_Size() int {
	return xxx_messageInfo_CancelAuctionRequest.Size(m)
}
func (m *CancelAuctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelAuctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelAuctionRequest proto.InternalMessageInfo

func (m *CancelAuctionRequest) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

type CancelAuctionResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelAuctionResponse) Reset()         { *m = CancelAuctionResponse{} }
func (m *CancelAuctionResponse) String() string { return proto.CompactTextString(m) }
func (*CancelAuctionResponse) ProtoMessage()    {}
func (*CancelAuctionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_323b9ee31d05cb8c, []int{5}
}

func (m *CancelAuctionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelAuctionResponse.Unmarshal(m, b)
}
func (m *CancelAuctionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelAuctionResponse.Marshal(b, m, deterministic)
}
func (m *CancelAuctionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelAuctionResponse.Merge(m, src)
}
func (m *CancelAuctionResponse) XXX_Size() int {
	return xxx_messageInfo_CancelAuctionResponse.Size(m)
}
func (m *CancelAuctionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelAuctionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelAuctionResponse proto.InternalMessageInfo

func (m *CancelAuctionResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CancelAuctionResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*StartAuctionRequest)(nil), "protobuf.StartAuctionRequest")
	proto.RegisterType((*StartAuctionResponse)(nil), "protobuf.StartAuctionResponse")
	proto.RegisterType((*SetStartTimeRequest)(nil), "protobuf.SetStartTimeRequest")
	proto.RegisterType((*SetStartTimeResponse)(nil), "protobuf.SetStartTimeResponse")
	proto.RegisterType((*CancelAuctionRequest)(nil), "protobuf.CancelAuctionRequest")
	proto.RegisterType((*CancelAuctionResponse)(nil), "protobuf.CancelAuctionResponse")
}

func init() {
	proto.RegisterFile("pkg/auctions-service/protobuf/auctions_management_service.proto", fileDescriptor_323b9ee31d05cb8c)
}

var fileDescriptor_323b9ee31d05cb8c = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4f, 0x4f, 0xbb, 0x40,
	0x10, 0x6d, 0xfb, 0x4b, 0x9b, 0x76, 0xf2, 0xf3, 0xb2, 0xad, 0x06, 0x49, 0xaa, 0x86, 0x93, 0x17,
	0x21, 0xd1, 0xea, 0xd5, 0xf8, 0xef, 0xe0, 0xc1, 0x98, 0x80, 0x27, 0x2f, 0x64, 0xa1, 0x63, 0x43,
	0x94, 0x5d, 0xdc, 0x5d, 0x3c, 0xf8, 0x2d, 0xfc, 0xc6, 0x86, 0x65, 0x21, 0xa0, 0xd4, 0x68, 0x8f,
	0xb3, 0x6f, 0xde, 0x9b, 0x97, 0x79, 0x3b, 0x70, 0x9e, 0x3d, 0xaf, 0x3c, 0x9a, 0xc7, 0x2a, 0xe1,
	0x4c, 0x1e, 0x49, 0x14, 0x6f, 0x49, 0x8c, 0x5e, 0x26, 0xb8, 0xe2, 0x51, 0xfe, 0x54, 0x23, 0x61,
	0x4a, 0x19, 0x5d, 0x61, 0x8a, 0x4c, 0x85, 0xa6, 0xc9, 0xd5, 0x4d, 0x64, 0x5c, 0xf5, 0x3a, 0x0b,
	0x98, 0x06, 0x8a, 0x0a, 0x75, 0x51, 0x72, 0x7c, 0x7c, 0xcd, 0x51, 0x2a, 0x32, 0x07, 0x30, 0x2a,
	0x61, 0xb2, 0xb4, 0xfa, 0x07, 0xfd, 0xc3, 0x89, 0x3f, 0x31, 0x2f, 0xb7, 0x4b, 0xe7, 0x1a, 0x66,
	0x6d, 0x96, 0xcc, 0x38, 0x93, 0x48, 0x76, 0x60, 0x24, 0x15, 0x55, 0xb9, 0xd4, 0x94, 0xa1, 0x6f,
	0x2a, 0x32, 0x83, 0x21, 0x0a, 0xc1, 0x85, 0x35, 0xd0, 0x4a, 0x65, 0xe1, 0x70, 0x98, 0x06, 0xa8,
	0xb4, 0xd0, 0x43, 0x92, 0xe2, 0xef, 0x66, 0x17, 0xb0, 0x2c, 0x28, 0xa1, 0x4a, 0x52, 0x34, 0x82,
	0x13, 0x59, 0x89, 0x10, 0x1b, 0xc6, 0x05, 0xf0, 0xce, 0x19, 0x5a, 0xff, 0x34, 0x58, 0xd7, 0xda,
	0x76, 0x6b, 0xe0, 0x46, 0xb6, 0x4f, 0x61, 0x76, 0x45, 0x59, 0x8c, 0x2f, 0x7f, 0xdb, 0xd9, 0x0d,
	0x6c, 0x7f, 0xa1, 0x6d, 0x32, 0xfd, 0xf8, 0x63, 0x00, 0xbb, 0x46, 0x41, 0xde, 0xd5, 0xf9, 0x06,
	0x65, 0xbc, 0xe4, 0x1e, 0xfe, 0x37, 0x83, 0x21, 0x73, 0xb7, 0x4a, 0xda, 0xed, 0x88, 0xd9, 0xde,
	0x5b, 0x07, 0x97, 0xd6, 0x9c, 0x1e, 0xf1, 0x61, 0xab, 0xe5, 0x9a, 0x34, 0x28, 0x5d, 0x5b, 0xb0,
	0xf7, 0xd7, 0xe2, 0xb5, 0x66, 0x61, 0xb2, 0x11, 0x43, 0xcb, 0xe4, 0xf7, 0xff, 0xd0, 0x32, 0xd9,
	0x91, 0x9e, 0xd3, 0xbb, 0x3c, 0x7b, 0x5c, 0x78, 0xdd, 0x27, 0x11, 0xfd, 0x74, 0x0c, 0xd1, 0x48,
	0x0b, 0x9f, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x1d, 0x9c, 0x5b, 0x50, 0x03, 0x00, 0x00,
}
