// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/auctions-service/protobuf/auctions_run_service.proto

package auctions_run_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SuggestPriceRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ProductID            string   `protobuf:"bytes,2,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	NewPrice             int64    `protobuf:"varint,3,opt,name=NewPrice,proto3" json:"NewPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuggestPriceRequest) Reset()         { *m = SuggestPriceRequest{} }
func (m *SuggestPriceRequest) String() string { return proto.CompactTextString(m) }
func (*SuggestPriceRequest) ProtoMessage()    {}
func (*SuggestPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20672060bc45ae6d, []int{0}
}

func (m *SuggestPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuggestPriceRequest.Unmarshal(m, b)
}
func (m *SuggestPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuggestPriceRequest.Marshal(b, m, deterministic)
}
func (m *SuggestPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuggestPriceRequest.Merge(m, src)
}
func (m *SuggestPriceRequest) XXX_Size() int {
	return xxx_messageInfo_SuggestPriceRequest.Size(m)
}
func (m *SuggestPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SuggestPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SuggestPriceRequest proto.InternalMessageInfo

func (m *SuggestPriceRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *SuggestPriceRequest) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *SuggestPriceRequest) GetNewPrice() int64 {
	if m != nil {
		return m.NewPrice
	}
	return 0
}

type SuggestPriceResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuggestPriceResponse) Reset()         { *m = SuggestPriceResponse{} }
func (m *SuggestPriceResponse) String() string { return proto.CompactTextString(m) }
func (*SuggestPriceResponse) ProtoMessage()    {}
func (*SuggestPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20672060bc45ae6d, []int{1}
}

func (m *SuggestPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuggestPriceResponse.Unmarshal(m, b)
}
func (m *SuggestPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuggestPriceResponse.Marshal(b, m, deterministic)
}
func (m *SuggestPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuggestPriceResponse.Merge(m, src)
}
func (m *SuggestPriceResponse) XXX_Size() int {
	return xxx_messageInfo_SuggestPriceResponse.Size(m)
}
func (m *SuggestPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuggestPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuggestPriceResponse proto.InternalMessageInfo

func (m *SuggestPriceResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SuggestPriceResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetCurrentPriceRequest struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentPriceRequest) Reset()         { *m = GetCurrentPriceRequest{} }
func (m *GetCurrentPriceRequest) String() string { return proto.CompactTextString(m) }
func (*GetCurrentPriceRequest) ProtoMessage()    {}
func (*GetCurrentPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20672060bc45ae6d, []int{2}
}

func (m *GetCurrentPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentPriceRequest.Unmarshal(m, b)
}
func (m *GetCurrentPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentPriceRequest.Marshal(b, m, deterministic)
}
func (m *GetCurrentPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentPriceRequest.Merge(m, src)
}
func (m *GetCurrentPriceRequest) XXX_Size() int {
	return xxx_messageInfo_GetCurrentPriceRequest.Size(m)
}
func (m *GetCurrentPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentPriceRequest proto.InternalMessageInfo

func (m *GetCurrentPriceRequest) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

type GetCurrentPriceResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Price                string   `protobuf:"bytes,2,opt,name=Price,proto3" json:"Price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentPriceResponse) Reset()         { *m = GetCurrentPriceResponse{} }
func (m *GetCurrentPriceResponse) String() string { return proto.CompactTextString(m) }
func (*GetCurrentPriceResponse) ProtoMessage()    {}
func (*GetCurrentPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20672060bc45ae6d, []int{3}
}

func (m *GetCurrentPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentPriceResponse.Unmarshal(m, b)
}
func (m *GetCurrentPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentPriceResponse.Marshal(b, m, deterministic)
}
func (m *GetCurrentPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentPriceResponse.Merge(m, src)
}
func (m *GetCurrentPriceResponse) XXX_Size() int {
	return xxx_messageInfo_GetCurrentPriceResponse.Size(m)
}
func (m *GetCurrentPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentPriceResponse proto.InternalMessageInfo

func (m *GetCurrentPriceResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetCurrentPriceResponse) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func init() {
	proto.RegisterType((*SuggestPriceRequest)(nil), "protobuf.SuggestPriceRequest")
	proto.RegisterType((*SuggestPriceResponse)(nil), "protobuf.SuggestPriceResponse")
	proto.RegisterType((*GetCurrentPriceRequest)(nil), "protobuf.GetCurrentPriceRequest")
	proto.RegisterType((*GetCurrentPriceResponse)(nil), "protobuf.GetCurrentPriceResponse")
}

func init() {
	proto.RegisterFile("pkg/auctions-service/protobuf/auctions_run_service.proto", fileDescriptor_20672060bc45ae6d)
}

var fileDescriptor_20672060bc45ae6d = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0x7d, 0x4b, 0x4b, 0x3b, 0x08, 0xc2, 0x5a, 0x6a, 0x09, 0x2a, 0x35, 0xa7, 0x5e,
	0x9a, 0x88, 0x82, 0x78, 0x55, 0x23, 0x52, 0x04, 0x2d, 0x29, 0x5e, 0x44, 0x28, 0x49, 0x1c, 0x43,
	0x10, 0x77, 0xe3, 0xfe, 0xd1, 0x0f, 0xe8, 0x17, 0x93, 0x6c, 0x36, 0xa9, 0xa9, 0xd1, 0xe3, 0xb3,
	0xb3, 0x33, 0xcf, 0x6f, 0x1e, 0x06, 0xce, 0xf2, 0x97, 0xd4, 0x8f, 0x74, 0xa2, 0x32, 0xce, 0xe4,
	0x4c, 0xa2, 0x78, 0xcf, 0x12, 0xf4, 0x73, 0xc1, 0x15, 0x8f, 0xf5, 0x73, 0x5d, 0x59, 0x09, 0xcd,
	0x56, 0xb6, 0xea, 0x99, 0x2a, 0xed, 0x57, 0x9f, 0xdc, 0x14, 0x76, 0x96, 0x3a, 0x4d, 0x51, 0xaa,
	0x85, 0xc8, 0x12, 0x0c, 0xf1, 0x4d, 0xa3, 0x54, 0x74, 0x04, 0xbd, 0x7b, 0x89, 0x62, 0x1e, 0x8c,
	0xc9, 0x84, 0x4c, 0x3b, 0xa1, 0x55, 0x74, 0x0f, 0x06, 0x0b, 0xc1, 0x9f, 0x74, 0xa2, 0xe6, 0xc1,
	0xf8, 0xff, 0x84, 0x4c, 0x07, 0xe1, 0xfa, 0x81, 0x3a, 0xd0, 0xbf, 0xc5, 0x0f, 0x33, 0x68, 0xdc,
	0x31, 0x7d, 0xb5, 0x76, 0x03, 0x18, 0x36, 0x8d, 0x64, 0xce, 0x99, 0xc4, 0xc2, 0x49, 0xaa, 0x48,
	0x69, 0x69, 0x9c, 0xba, 0xa1, 0x55, 0x74, 0x08, 0xdd, 0x2b, 0x21, 0xb8, 0xb0, 0x2e, 0xa5, 0x70,
	0x4f, 0x61, 0x74, 0x8d, 0xea, 0x52, 0x0b, 0x81, 0xac, 0x49, 0xdc, 0x20, 0x23, 0x1b, 0x64, 0xee,
	0x0d, 0xec, 0xfe, 0xe8, 0xb3, 0x00, 0x0e, 0xf4, 0x8b, 0xe5, 0x58, 0xf4, 0x8a, 0xb6, 0xaf, 0xd6,
	0x05, 0x44, 0xb9, 0x8d, 0x85, 0x30, 0xe2, 0xf8, 0x93, 0x00, 0x0d, 0x35, 0x3b, 0xb7, 0xf9, 0x2e,
	0xcb, 0x68, 0xe9, 0x1d, 0x6c, 0x7d, 0xdf, 0x90, 0xee, 0x7b, 0x55, 0xca, 0x5e, 0x4b, 0xc4, 0xce,
	0xc1, 0x6f, 0xe5, 0x92, 0xcb, 0xfd, 0x47, 0x1f, 0x61, 0x7b, 0x03, 0x9a, 0x4e, 0xd6, 0x4d, 0xed,
	0x39, 0x38, 0x87, 0x7f, 0xfc, 0xa8, 0x26, 0x4f, 0xc9, 0x11, 0xb9, 0xf0, 0x1f, 0x66, 0x7e, 0xfb,
	0x01, 0xc5, 0xad, 0xa7, 0x13, 0xf7, 0xcc, 0xe0, 0x93, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b,
	0x44, 0x3b, 0x2a, 0x77, 0x02, 0x00, 0x00,
}
